version: '3.7'
services:
  application:
    build: .
    restart: always
    ports:
      - 8888:8888
    links:
      - mongodb:database
  mongodb:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017